### ISSUE TITLE
Plot range doesn't conform to mathematica standard

### ISSUE THREAD

**Issue by reinthal** [cekdahl/PhasePortrait#1]
Hi,

Using this package in class right now. Plot range arguments are passed in this fashion

```
PhasePortrait[{
  x'[t] == f[x[t],y[t]],
  y'[t] == g[x[t],y[t]]
  }, {x, y}, t, {{**x_min, y_min**}, {**x_max, y_max**}},
 PortraitDensity -> 12
 ]
```
The rest of mathematica passes arguments like this

`{{**x_min, x_max**}, {**y_min, y_max**}}`

Room for improvement!

**Comment by cekdahl** [comment]
I agree that most expect this argument to behave like `PlotRange` and I might change it to this format as a part of a larger update in the future. It is currently using the format that `Rectangle` also uses, so it's not something that's completely new to Mathematica users but it's not most users' first guess. Thank you for the feedback.
